services:
  azura-framework:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # read_only: true
    restart: always
    mem_limit: 16g
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    image: git.azuratech.com:3000/core/azura-framework:latest
    container_name: azura-framework
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - azura_services_azura-network
networks:
    azura_services_azura-network:
      external: true