<template>
  <div class="icon-select-container">
    <el-popover
      placement="bottom-start"
      :width="420"
      trigger="click"
      v-model:visible="popoverVisible"
    >
      <template #reference>
        <el-input
          v-model="currentIcon"
          placeholder="点击选择菜单图标"
          readonly
          clearable
          @clear="clearIcon"
        >
          <template #prefix>
            <el-icon v-if="currentIcon && isElementIcon(currentIcon)" class="el-input__icon">
              <component :is="currentIcon" />
            </el-icon>
            <svg v-else-if="currentIcon" class="icon-svg" aria-hidden="true">
              <use :xlink:href="`#${currentIcon}`"></use>
            </svg>
            <el-icon v-else class="el-input__icon"><Search /></el-icon>
          </template>
        </el-input>
      </template>

      <div class="icon-selector-body">
        <el-input
          v-model="searchText"
          placeholder="搜索图标名称..."
          clearable
          prefix-icon="Search"
          class="search-input"
        />

        <el-tabs v-model="activeTab">
          <el-tab-pane label="Element Plus" name="element">
            <el-scrollbar height="220px">
              <div class="icon-grid">
                <div
                  v-for="icon in filteredElementIcons"
                  :key="icon"
                  class="icon-item"
                  :class="{ 'is-active': currentIcon === icon }"
                  @click="selectIcon(icon)"
                  :title="icon"
                >
                  <el-icon><component :is="icon" /></el-icon>
                </div>
                <el-empty
                  v-if="filteredElementIcons.length === 0"
                  description="未找到匹配的图标"
                  :image-size="40"
                />
              </div>
            </el-scrollbar>
          </el-tab-pane>

          <el-tab-pane label="Iconfont" name="iconfont">
            <el-scrollbar height="220px">
              <div class="icon-grid">
                <div
                  v-for="icon in filteredIconfont"
                  :key="icon"
                  class="icon-item"
                  :class="{ 'is-active': currentIcon === icon }"
                  @click="selectIcon(icon)"
                  :title="icon"
                >
                  <svg class="icon-svg" aria-hidden="true">
                    <use :xlink:href="`#${icon}`"></use>
                  </svg>
                </div>
                <el-empty
                  v-if="filteredIconfont.length === 0"
                  description="未找到匹配的图标"
                  :image-size="40"
                />
              </div>
            </el-scrollbar>
          </el-tab-pane>
        </el-tabs>
      </div>
    </el-popover>
  </div>
</template>

<script setup lang="ts">
  import { ref, computed } from 'vue';
  import * as ElementPlusIconsVue from '@element-plus/icons-vue';
  import { iconfontList as autoGeneratedList } from '@/config/iconfont-data';
  const props = defineProps({
    modelValue: {
      type: String,
      default: ''
    }
  });

  const emit = defineEmits(['update:modelValue']);

  const popoverVisible = ref(false);
  const activeTab = ref('element');
  const searchText = ref('');

  // 双向绑定当前的图标
  const currentIcon = computed({
    get: () => props.modelValue,
    set: (val) => emit('update:modelValue', val)
  });

  // ---------------- Element Plus 图标逻辑 ----------------
  // 提取所有 Element Plus 图标组件名称
  const elementIcons = Object.keys(ElementPlusIconsVue);

  const filteredElementIcons = computed(() => {
    if (!searchText.value) return elementIcons;
    return elementIcons.filter((icon) =>
      icon.toLowerCase().includes(searchText.value.toLowerCase())
    );
  });

  const isElementIcon = (iconName: string) => {
    return elementIcons.includes(iconName);
  };

  // ---------------- Iconfont 图标逻辑 ----------------
  const iconfontList = ref(autoGeneratedList);

  const filteredIconfont = computed(() => {
    if (!searchText.value) return iconfontList.value;
    return iconfontList.value.filter((icon) =>
      icon.toLowerCase().includes(searchText.value.toLowerCase())
    );
  });

  // ---------------- 交互逻辑 ----------------
  const selectIcon = (iconName: string) => {
    currentIcon.value = iconName;
    popoverVisible.value = false; // 选择后自动关闭
  };

  const clearIcon = () => {
    currentIcon.value = '';
    emit('update:modelValue', '');
  };
</script>

<style lang="scss" scoped>
  .icon-selector-body {
    display: flex;
    flex-direction: column;
  }
  .search-input {
    margin-bottom: 10px;
  }
  .icon-grid {
    display: grid;
    grid-template-columns: repeat(8, 1fr);
    gap: 8px;
    padding: 4px;
  }
  .icon-item {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 36px;
    font-size: 18px;
    cursor: pointer;
    border: 1px solid #e4e7ed;
    border-radius: 4px;
    transition: all 0.2s;
  }
  .icon-item:hover {
    background-color: #f5f7fa;
    color: var(--el-color-primary);
    border-color: var(--el-color-primary);
  }
  .icon-item.is-active {
    background-color: var(--el-color-primary-light-9);
    color: var(--el-color-primary);
    border-color: var(--el-color-primary);
  }

  /* 统一设置弹出层内所有图标（Element & Iconfont）的大小 */
  .icon-item .el-icon {
    font-size: 20px; /* 根据你的喜好调大，20px 通常比较饱满 */
  }

  .icon-item .iconfont {
    font-size: 20px; /* 强制 Iconfont 也变成同样的大小 */
  }

  /* 顺便修复一下输入框左侧的前缀图标大小，让它也饱满一些 */
  .el-input__prefix .el-input__icon.iconfont {
    font-size: 16px; /* 输入框里的图标通常比弹出层里小一点 */
    display: flex;
    align-items: center;
    justify-content: center;
  }
</style>
