services:
  azura-framework-serve:
    image: azura-framework-serve:latest
    container_name: azura-framework-serve
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "2000:3000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - azura_services_azura-network

networks:
  azura_services_azura-network:
    external: true

